baseURL = 'https://stackedbytes.dev/'
languageCode = 'en-us'
title = 'Stacked Bytes'
#theme = 'pehtheme-hugo'

#paginate = '6' # <- Set the desired number of posts per page
summaryLength = '20' # <- 20 words are approximately 160 characters


[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Stacked Bytes'
	mainSections = 'posts'

[author]
[author.beat]
	name = 'Beat Rupp'
	email = 'beat@rupp.digital'
	bio = 'Freelance iOS Developer'
	avatar = 'images/br_avatar_padding.png'
	twitter = 'https://twitter.com/beatrupp'
[author.ben]
    name = 'Ben Rudhart'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
#  [module.mounts] # Directing the static folder to assets.
#  	source = 'assets'
#  	target = 'static'
